name = "snaptik-prod2"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Workers Sites configuration for static assets
[site]
bucket = "."
include = ["index.html", "css/*", "js/*"]

# Bindings
[vars]
ENVIRONMENT = "production"
